export const environment = {
  production: true,
  CookieKey: "AngularDemoUserData",
  WebAPIURL: "http://192.168.0.102/",
  Register:"",
  Login:"",
  GetUsers:"",
  NewUser:"",
  GetUser:"getuser",
  UpdateUser:"",
  DeleteUser:"",
  AssignRole:"",
  GetRoles:"",
  NewRole:"",
  GetRole:"",
  UpdateRole:"",
  DeleteRole:"",
  AssignPermissions:"",
  GetPermissions:"",
  NewPermission:"",
  GetPermission:"",
  UpdatePermission:"",
  DeletePermission:"",
};
